[package]
name = "atuin-client"
edition = "2024"
description = "client library for atuin"

rust-version = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atuin-common = { path = "../atuin-common", version = "18.13.3" }

log = { workspace = true }
time = { workspace = true, features = ["macros", "formatting", "parsing"] }
clap = { workspace = true }
eyre = { workspace = true }
directories = { workspace = true }
uuid = { workspace = true }
whoami = { workspace = true }
interim = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
shellexpand = "3"
sqlx = { workspace = true, features = ["sqlite", "regexp"] }
minspan = "0.1.5"
regex = "1.10.5"
serde_regex = "1.1.0"
fs-err = { workspace = true }
sql-builder = { workspace = true }
memchr = "2.7"
rmp = { version = "0.8.14" }
typed-builder = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
futures = "0.3"
notify = "7"
serde_with = "3.8.1"

# theme
crossterm = { workspace = true, features = ["serde"] }
palette = { version = "0.7.5", features = ["serializing"] }
strum_macros = "0.27"
strum = { version = "0.27", features = ["strum_macros"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
pretty_assertions = { workspace = true }
testing_logger = "0.1.1"
